# 
#  english.yml
#  PIM
#  
#  Created by Kael Hankins on 2013-01-10.
#  Copyright 2013 Kael Hankins. All rights reserved.
# 
#  This file holds the string definitions for PIM to make for easy language adaptation later.

