# 
#  english.yml
#  PIM
#  
#  Created by Kael Hankins on 2013-01-10.
#  Copyright 2013 Kael Hankins. All rights reserved.
# 
#  This file holds the string definitions for PIM to make for easy language adaptation later.
#  All printed, human read strings should be defined here.
#  The server must be restarted to show changes to this file as it is only read on startup.

home_footer: "Home Page Footer"

blog_title: "News and Updates"
blog_footer: "Blog Footer goes here."

#Notices
new-pim-admin-success: "A new PIM admin was created."
edit-pim-admin-success: "The PIM admin was edited."
destroy-pim-admin-success: "The PIM admin was deleted."

#Error Messages

#Posts
last-updated: "Last Updated"
created: "Created"
posted: "Posted"
new-post: "New Post"
by: "By"
sorry-no-posts: "Sorry, there are no posts yet!"

#PIM Admins
sorry-no-admins: "Sorry, there are no PIM admins."
first-name: "First Name"
last-name: "Last Name"
username: "Username"
email: "Email"
email-address: "Email Address"
